### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by tmr83** [sultan-of-rum/morrowind-scripting-for-dummies#4]
A few things about them currently: first, I want to remove the smilies, and I want to replace the Tribunal and Bloodmoon graphics with text. This way, it reduces the size and complexity of using them in the document. A couple graphics could also benefit from being updated.

**Comment by tmr83** [comment]
This page has some updated graphics: https://en.m.uesp.net/wiki/Morrowind_Mod:Scripting_for_Dummies. I wonder if we can use them.

**Comment by tmr83** [comment]
Here is an example of graphics created on Linux with Gnome3 and dark mode on. It's much more modern looking, but I am wondering if Windows users will get distracted. The script text is missing because it didn't save without giving me a bunch of errors, so I am wondering if there is a good candidate for replacement as well.

![Screenshot from 2021-08-29 14-19-07](https://user-images.githubusercontent.com/80742709/131263168-49e53cba-5314-4155-8e53-dba91e42ae9a.png)

And just for contrast, openCS:

![Screenshot from 2021-08-29 14-33-42](https://user-images.githubusercontent.com/80742709/131263172-34ca57e0-f43c-4b06-b765-6c29655724c9.png)

**Comment by sultan-of-rum** [comment]
I think the GNOME graphics are fine -- the difference is minimal and the text itself is of such a technical nature that I doubt much of the readership will get too distracted.

For the non-compiling script -- can't you just paste the script text into the window for screenshot purposes? Or does it need to be saved for some reason I don't understand?

**Comment by tmr83** [comment]
Yes, I can cut and paste the text for the screenshot. Before, I was trying to get the image as close to the original as possible.

**Comment by tmr83** [comment]
I am unable to provide replacements for images 2 and 4. @sultan-of-rum do you mind providing them for me?

**Comment by tmr83** [comment]
I added new modern looking graphics with a0254b67d62ec6e7d3d4743c83d62ba7c2117694.
